-- Manager.io invoice sync and component stock foundation
-- Run this after 001_rbac_foundation.sql.

-- ------------------------------------------------------------
-- Component stock fields
-- ------------------------------------------------------------

ALTER TABLE public.components
  ADD COLUMN IF NOT EXISTS component_sku_normalized text,
  ADD COLUMN IF NOT EXISTS current_stock numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stock_unit text,
  ADD COLUMN IF NOT EXISTS minimum_stock numeric,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.components
SET component_sku_normalized = lower(trim(component_sku))
WHERE component_sku IS NOT NULL
  AND component_sku_normalized IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_components_component_sku_normalized
  ON public.components(component_sku_normalized)
  WHERE component_sku_normalized IS NOT NULL;

DROP TRIGGER IF EXISTS set_components_updated_at ON public.components;
CREATE TRIGGER set_components_updated_at
BEFORE UPDATE ON public.components
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- ------------------------------------------------------------
-- Product bill of materials / component recipe
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.product_components (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  component_id bigint NOT NULL REFERENCES public.components(id) ON DELETE RESTRICT,
  quantity_required numeric NOT NULL DEFAULT 1,
  wastage_percentage numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_components_quantity_required_positive CHECK (quantity_required > 0),
  CONSTRAINT product_components_wastage_percentage_non_negative CHECK (wastage_percentage >= 0),
  CONSTRAINT product_components_unique_pair UNIQUE (product_id, component_id)
);

DROP TRIGGER IF EXISTS set_product_components_updated_at ON public.product_components;
CREATE TRIGGER set_product_components_updated_at
BEFORE UPDATE ON public.product_components
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_product_components_product_id
  ON public.product_components(product_id);

CREATE INDEX IF NOT EXISTS idx_product_components_component_id
  ON public.product_components(component_id);

-- ------------------------------------------------------------
-- Manager invoice import tracking
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.manager_sync_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running',
  invoices_seen integer NOT NULL DEFAULT 0,
  invoices_imported integer NOT NULL DEFAULT 0,
  invoices_skipped integer NOT NULL DEFAULT 0,
  stock_movements_created integer NOT NULL DEFAULT 0,
  error_message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT manager_sync_runs_status_check CHECK (status IN ('running', 'completed', 'failed'))
);

CREATE TABLE IF NOT EXISTS public.manager_invoice_imports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  manager_invoice_id text NOT NULL UNIQUE,
  invoice_number text,
  invoice_date date,
  customer_name text,
  status text,
  raw_invoice jsonb NOT NULL DEFAULT '{}'::jsonb,
  processed_at timestamptz NOT NULL DEFAULT now(),
  sync_run_id uuid REFERENCES public.manager_sync_runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_manager_invoice_imports_invoice_date
  ON public.manager_invoice_imports(invoice_date);

CREATE INDEX IF NOT EXISTS idx_manager_invoice_imports_sync_run_id
  ON public.manager_invoice_imports(sync_run_id);

-- ------------------------------------------------------------
-- Stock movements generated by invoices
-- quantity_delta is negative when stock is consumed.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.component_stock_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  component_id bigint NOT NULL REFERENCES public.components(id) ON DELETE RESTRICT,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  manager_invoice_import_id uuid REFERENCES public.manager_invoice_imports(id) ON DELETE SET NULL,
  source_type text NOT NULL DEFAULT 'manager_sales_invoice',
  source_reference text,
  quantity_delta numeric NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_component_stock_movements_component_id
  ON public.component_stock_movements(component_id);

CREATE INDEX IF NOT EXISTS idx_component_stock_movements_product_id
  ON public.component_stock_movements(product_id);

CREATE INDEX IF NOT EXISTS idx_component_stock_movements_invoice_import_id
  ON public.component_stock_movements(manager_invoice_import_id);

-- ------------------------------------------------------------
-- Helper to apply stock movements consistently
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.apply_component_stock_movement(
  target_component_id bigint,
  target_product_id uuid,
  target_invoice_import_id uuid,
  target_source_reference text,
  target_quantity_delta numeric,
  target_notes text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_movement_id uuid;
BEGIN
  INSERT INTO public.component_stock_movements (
    component_id,
    product_id,
    manager_invoice_import_id,
    source_reference,
    quantity_delta,
    notes,
    created_by
  )
  VALUES (
    target_component_id,
    target_product_id,
    target_invoice_import_id,
    target_source_reference,
    target_quantity_delta,
    target_notes,
    auth.uid()
  )
  RETURNING id INTO new_movement_id;

  UPDATE public.components
  SET current_stock = current_stock + target_quantity_delta
  WHERE id = target_component_id;

  RETURN new_movement_id;
END;
$$;

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------

ALTER TABLE public.product_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manager_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manager_invoice_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.component_stock_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users with components.view can read product components" ON public.product_components;
CREATE POLICY "Users with components.view can read product components"
ON public.product_components
FOR SELECT
TO authenticated
USING (public.current_user_has_permission('components.view'));

DROP POLICY IF EXISTS "Users with components.update can manage product components" ON public.product_components;
CREATE POLICY "Users with components.update can manage product components"
ON public.product_components
FOR ALL
TO authenticated
USING (public.current_user_has_permission('components.update'))
WITH CHECK (public.current_user_has_permission('components.update'));

DROP POLICY IF EXISTS "Users with stock.view can read manager sync runs" ON public.manager_sync_runs;
CREATE POLICY "Users with stock.view can read manager sync runs"
ON public.manager_sync_runs
FOR SELECT
TO authenticated
USING (public.current_user_has_permission('stock.view'));

DROP POLICY IF EXISTS "Users with stock.view can read manager invoices" ON public.manager_invoice_imports;
CREATE POLICY "Users with stock.view can read manager invoices"
ON public.manager_invoice_imports
FOR SELECT
TO authenticated
USING (public.current_user_has_permission('stock.view'));

DROP POLICY IF EXISTS "Users with stock.view can read stock movements" ON public.component_stock_movements;
CREATE POLICY "Users with stock.view can read stock movements"
ON public.component_stock_movements
FOR SELECT
TO authenticated
USING (public.current_user_has_permission('stock.view'));

-- Writes to manager_sync_runs, manager_invoice_imports and component_stock_movements
-- should be performed by server-side code using the service role key.
